### ISSUE TITLE
Automatically call pthread_init on main thread.

### ISSUE THREAD

**Issue by DaveeFTW** [vitasdk/newlib#11]
If developers are using the c++11 std::thread class then it will crash when invoking the underlying pthread implementation. This is because the starting thread does not have the correct context information setup in its TLS.
There should be some mechanism in place to automatically call pthread_init on the main thread prior to main() when pthread is linked.

**Comment by frangarcj** [comment]
#17

**Comment by frangarcj** [comment]
https://github.com/vitasdk/vita-toolchain/issues/103
