### ISSUE TITLE
Missing functionality for MegaZeux port

### ISSUE THREAD

**Issue by asiekierka** [vitasdk/newlib#36]
I have identified four missing methods for a port of the game creation system MegaZeux to the PlayStation Vita: getcwd, chdir, mkdir, rmdir. (I think they're missing, but I'm not 100% sure - perhaps 90%)

* mkdir/rmdir: It appears that the Vita's own headers provide sufficiently equivalent functions - wrapping them would probably be feasible and not too difficult.
* getcwd/chdir: I'm... not sure about the feasibility of these.

**Comment by Rinnegatamante** [comment]
mkdir can be replaced with sceIoMkdir, same for rmdir with sceIoRemove.
getcwd and chdir are not available on Vita. All the current game ports using them just replace them with an handmade version or with absolute paths.

**Comment by devnoname120** [comment]
Note that `getcwd` / `chdir` can definitely be implemented, it would require modifying functions such as `fopen`, `opendir`, etc. so that they take it in account.

**Comment by isage** [comment]
Fixed in #68
